import type { HearthDeck } from './effects/registry';

/** 2026 强化扩展；旧版 starter 牌组加载时会自动补齐每张两份。 */
export const HEARTH_EXPANSION_CARD_IDS = [
  'berserkerOath',
  'vitalSurge',
  'warcryCommander',
  'bloodforgeColossus',
  'goldenCitadel',
  'agonyDevourer',
  'unoAnnihilation',
  'forcedConscription',
  'bloodMeasureArbiter',
  'battlefieldRotation',
  'duelOfAllegiance',
  'armyExchange',
  'chaosConscription',
  'equalityOfAll',
  'formationCommander',
] as const;

/**
 * 预设炉石牌组。强力随从均放入两张，避免在长牌池中迟迟抽不到。
 */
export const PRESET_DECKS: HearthDeck[] = [
  {
    id: 'combo',
    name: '连击流',
    description: '大量抽牌与额外行动，快速出完 Uno 牌',
    cardIds: [
      'draw2',
      'draw2',
      'double',
      'double',
      'shield',
      'shield',
      'crystal2',
      'crystal2',
      'bolt',
      'arcaneArchive',
      'arcaneArchive',
      'clockworkSquire',
      'emberWolf',
      'fatefulGift',
      'fatefulGift',
      'chromaticConductor',
      'chromaticConductor',
      'crystalGuardian',
      'bloodboundTitan',
      'bloodboundTitan',
      'spyglassOracle',
      'spyglassOracle',
      'ashPhoenix',
      'ashPhoenix',
      'graveArchivist',
      'graveArchivist',
      'calamityDealer',
      'calamityDealer',
      'penaltyBulwark',
      'penaltyBulwark',
      'voidGambler',
      'voidGambler',
      'penitentChampion',
      'penitentChampion',
      'polymorph',
      'polymorph',
      'equalityOfAll',
      'equalityOfAll',
      'powerAcolyte',
      'powerAcolyte',
      'powerUnbound',
      'powerUnbound',
      'berserkerOath',
      'berserkerOath',
      'vitalSurge',
      'vitalSurge',
      'bloodMeasureArbiter',
      'bloodMeasureArbiter',
      'forcedConscription',
      'forcedConscription',
      'warcryCommander',
      'warcryCommander',
      'bloodforgeColossus',
      'bloodforgeColossus',
      'goldenCitadel',
      'goldenCitadel',
      'agonyDevourer',
      'agonyDevourer',
      'unoAnnihilation',
      'unoAnnihilation',
      'battlefieldRotation',
      'battlefieldRotation',
      'duelOfAllegiance',
      'duelOfAllegiance',
      'armyExchange',
      'armyExchange',
      'chaosConscription',
      'chaosConscription',
      'formationCommander',
      'formationCommander',
    ],
  },
  {
    id: 'burst',
    name: '爆发流',
    description: '高水晶产出 + 大量罚抽，压制对手',
    cardIds: [
      'untap',
      'untap',
      'crystal2',
      'fireball',
      'fireball',
      'bolt',
      'bolt',
      'massSkip',
      'manaBlast',
      'shield',
      'arcaneArchive',
      'arcaneArchive',
      'emberWolf',
      'emberWolf',
      'fatefulGift',
      'fatefulGift',
      'chromaticConductor',
      'chromaticConductor',
      'crystalGuardian',
      'stormDrake',
      'bloodboundTitan',
      'bloodboundTitan',
      'spyglassOracle',
      'spyglassOracle',
      'ashPhoenix',
      'ashPhoenix',
      'graveArchivist',
      'graveArchivist',
      'calamityDealer',
      'calamityDealer',
      'penaltyBulwark',
      'penaltyBulwark',
      'voidGambler',
      'voidGambler',
      'penitentChampion',
      'penitentChampion',
      'polymorph',
      'polymorph',
      'equalityOfAll',
      'equalityOfAll',
      'powerAcolyte',
      'powerAcolyte',
      'powerUnbound',
      'powerUnbound',
      'stormDrake',
      'crystalGuardian',
      'manaBlast',
      'crystal2',
      'bloodMeasureArbiter',
      'bloodMeasureArbiter',
      'warcryCommander',
      'warcryCommander',
      'bloodforgeColossus',
      'bloodforgeColossus',
      'goldenCitadel',
      'goldenCitadel',
      'agonyDevourer',
      'agonyDevourer',
      'unoAnnihilation',
      'unoAnnihilation',
      'battlefieldRotation',
      'battlefieldRotation',
      'duelOfAllegiance',
      'duelOfAllegiance',
      'armyExchange',
      'armyExchange',
      'chaosConscription',
      'chaosConscription',
      'formationCommander',
      'formationCommander',
    ],
  },
];

/** 默认牌组（单人/快速对战） */
export const DEFAULT_DECK_ID = 'combo';

export function getDeck(id: string): HearthDeck {
  return PRESET_DECKS.find((d) => d.id === id) ?? PRESET_DECKS[0]!;
}
