import type { HearthDeck } from './effects/registry';

/** 2026 强化扩展；旧版 starter 牌组加载时会在剩余容量内自动补齐。 */
export const HEARTH_EXPANSION_CARD_IDS = [
  'berserkerOath',
  'vitalSurge',
  'warcryCommander',
  'bloodforgeColossus',
  'goldenCitadel',
  'agonyDevourer',
  'unoAnnihilation',
  'forcedConscription',
  'bloodMeasureArbiter',
  'battlefieldRotation',
  'duelOfAllegiance',
  'armyExchange',
  'chaosConscription',
  'equalityOfAll',
  'formationCommander',
  'doomDealer',
  'cinderSweep',
  'unstableNova',
  'finalCollapse',
  'dustchargeSapper',
  'apocalypseHerald',
  'thunderhoofVanguard',
  'meteorLancer',
] as const;

/** 默认扩展牌补两张；极高压的厄运司牌者只补一张。 */
export const HEARTH_EXPANSION_CARD_COPIES: Partial<
  Record<(typeof HEARTH_EXPANSION_CARD_IDS)[number], number>
> = { doomDealer: 1, finalCollapse: 1, apocalypseHerald: 1 };

/** 50 张预设炉石牌组：保留完整功能覆盖，流派核心牌放入第二张。 */
export const PRESET_DECKS: HearthDeck[] = [
  {
    id: 'combo',
    name: '连击流',
    description: '大量抽牌与额外行动，快速出完 Uno 牌',
    cardIds: [
      'draw2',
      'draw2',
      'double',
      'double',
      'shield',
      'crystal2',
      'bolt',
      'arcaneArchive',
      'arcaneArchive',
      'clockworkSquire',
      'emberWolf',
      'thunderhoofVanguard',
      'fatefulGift',
      'fatefulGift',
      'chromaticConductor',
      'crystalGuardian',
      'bloodboundTitan',
      'spyglassOracle',
      'spyglassOracle',
      'ashPhoenix',
      'graveArchivist',
      'calamityDealer',
      'doomDealer',
      'penaltyBulwark',
      'voidGambler',
      'penitentChampion',
      'polymorph',
      'equalityOfAll',
      'powerAcolyte',
      'powerUnbound',
      'berserkerOath',
      'vitalSurge',
      'bloodMeasureArbiter',
      'forcedConscription',
      'warcryCommander',
      'bloodforgeColossus',
      'goldenCitadel',
      'agonyDevourer',
      'unoAnnihilation',
      'battlefieldRotation',
      'duelOfAllegiance',
      'armyExchange',
      'chaosConscription',
      'formationCommander',
      'cinderSweep',
      'dustchargeSapper',
      'unstableNova',
      'finalCollapse',
      'apocalypseHerald',
      'meteorLancer',
    ],
  },
  {
    id: 'burst',
    name: '爆发流',
    description: '高水晶产出 + 大量罚抽，压制对手',
    cardIds: [
      'untap',
      'crystal2',
      'crystal2',
      'fireball',
      'fireball',
      'bolt',
      'bolt',
      'massSkip',
      'manaBlast',
      'manaBlast',
      'shield',
      'arcaneArchive',
      'emberWolf',
      'thunderhoofVanguard',
      'thunderhoofVanguard',
      'fatefulGift',
      'chromaticConductor',
      'crystalGuardian',
      'stormDrake',
      'bloodboundTitan',
      'spyglassOracle',
      'ashPhoenix',
      'graveArchivist',
      'calamityDealer',
      'doomDealer',
      'penaltyBulwark',
      'voidGambler',
      'penitentChampion',
      'polymorph',
      'equalityOfAll',
      'powerAcolyte',
      'powerUnbound',
      'bloodMeasureArbiter',
      'warcryCommander',
      'bloodforgeColossus',
      'goldenCitadel',
      'agonyDevourer',
      'unoAnnihilation',
      'battlefieldRotation',
      'duelOfAllegiance',
      'armyExchange',
      'chaosConscription',
      'formationCommander',
      'cinderSweep',
      'dustchargeSapper',
      'unstableNova',
      'unstableNova',
      'finalCollapse',
      'apocalypseHerald',
      'meteorLancer',
    ],
  },
];

/** 默认牌组（单人/快速对战） */
export const DEFAULT_DECK_ID = 'combo';

export function getDeck(id: string): HearthDeck {
  return PRESET_DECKS.find((d) => d.id === id) ?? PRESET_DECKS[0]!;
}
